// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: offchainreporting3_1_jmt.proto

package serialization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Node:
	//
	//	*Node_InternalNode
	//	*Node_LeafNode
	Node isNode_Node `protobuf_oneof:"node"`
}

func (x *Node) Reset() {
	*x = Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offchainreporting3_1_jmt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_offchainreporting3_1_jmt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_offchainreporting3_1_jmt_proto_rawDescGZIP(), []int{0}
}

func (m *Node) GetNode() isNode_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (x *Node) GetInternalNode() *InternalNode {
	if x, ok := x.GetNode().(*Node_InternalNode); ok {
		return x.InternalNode
	}
	return nil
}

func (x *Node) GetLeafNode() *LeafNode {
	if x, ok := x.GetNode().(*Node_LeafNode); ok {
		return x.LeafNode
	}
	return nil
}

type isNode_Node interface {
	isNode_Node()
}

type Node_InternalNode struct {
	InternalNode *InternalNode `protobuf:"bytes,1,opt,name=internal_node,json=internalNode,proto3,oneof"`
}

type Node_LeafNode struct {
	LeafNode *LeafNode `protobuf:"bytes,2,opt,name=leaf_node,json=leafNode,proto3,oneof"`
}

func (*Node_InternalNode) isNode_Node() {}

func (*Node_LeafNode) isNode_Node() {}

type InternalNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Maps nibbles to children. The nibble for children[i] is the index of the
	// i-th 1 bit from LSB.
	ChildrenBitmap uint32 `protobuf:"varint,1,opt,name=children_bitmap,json=childrenBitmap,proto3" json:"children_bitmap,omitempty"`
	// Only non-nil children are included in this array, in nibble order.
	Children []*InternalNodeChild `protobuf:"bytes,2,rep,name=children,proto3" json:"children,omitempty"`
}

func (x *InternalNode) Reset() {
	*x = InternalNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offchainreporting3_1_jmt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalNode) ProtoMessage() {}

func (x *InternalNode) ProtoReflect() protoreflect.Message {
	mi := &file_offchainreporting3_1_jmt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalNode.ProtoReflect.Descriptor instead.
func (*InternalNode) Descriptor() ([]byte, []int) {
	return file_offchainreporting3_1_jmt_proto_rawDescGZIP(), []int{1}
}

func (x *InternalNode) GetChildrenBitmap() uint32 {
	if x != nil {
		return x.ChildrenBitmap
	}
	return 0
}

func (x *InternalNode) GetChildren() []*InternalNodeChild {
	if x != nil {
		return x.Children
	}
	return nil
}

type InternalNodeChild struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version uint64 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Digest  []byte `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	IsLeaf  bool   `protobuf:"varint,3,opt,name=is_leaf,json=isLeaf,proto3" json:"is_leaf,omitempty"`
}

func (x *InternalNodeChild) Reset() {
	*x = InternalNodeChild{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offchainreporting3_1_jmt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InternalNodeChild) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalNodeChild) ProtoMessage() {}

func (x *InternalNodeChild) ProtoReflect() protoreflect.Message {
	mi := &file_offchainreporting3_1_jmt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalNodeChild.ProtoReflect.Descriptor instead.
func (*InternalNodeChild) Descriptor() ([]byte, []int) {
	return file_offchainreporting3_1_jmt_proto_rawDescGZIP(), []int{2}
}

func (x *InternalNodeChild) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *InternalNodeChild) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *InternalNodeChild) GetIsLeaf() bool {
	if x != nil {
		return x.IsLeaf
	}
	return false
}

type LeafNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	KeyDigest   []byte `protobuf:"bytes,1,opt,name=key_digest,json=keyDigest,proto3" json:"key_digest,omitempty"`
	Key         []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	ValueDigest []byte `protobuf:"bytes,3,opt,name=value_digest,json=valueDigest,proto3" json:"value_digest,omitempty"`
	Value       []byte `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LeafNode) Reset() {
	*x = LeafNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offchainreporting3_1_jmt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LeafNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeafNode) ProtoMessage() {}

func (x *LeafNode) ProtoReflect() protoreflect.Message {
	mi := &file_offchainreporting3_1_jmt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeafNode.ProtoReflect.Descriptor instead.
func (*LeafNode) Descriptor() ([]byte, []int) {
	return file_offchainreporting3_1_jmt_proto_rawDescGZIP(), []int{3}
}

func (x *LeafNode) GetKeyDigest() []byte {
	if x != nil {
		return x.KeyDigest
	}
	return nil
}

func (x *LeafNode) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *LeafNode) GetValueDigest() []byte {
	if x != nil {
		return x.ValueDigest
	}
	return nil
}

func (x *LeafNode) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

var File_offchainreporting3_1_jmt_proto protoreflect.FileDescriptor

var file_offchainreporting3_1_jmt_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x33, 0x5f, 0x31, 0x5f, 0x6a, 0x6d, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x14, 0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x33, 0x5f, 0x31, 0x22, 0x98, 0x01, 0x0a, 0x04, 0x4e, 0x6f, 0x64, 0x65, 0x12,
	0x49, 0x0a, 0x0d, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x5f, 0x6e, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69,
	0x6e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67, 0x33, 0x5f, 0x31, 0x2e, 0x49, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x69, 0x6e,
	0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x3d, 0x0a, 0x09, 0x6c, 0x65,
	0x61, 0x66, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e,
	0x67, 0x33, 0x5f, 0x31, 0x2e, 0x4c, 0x65, 0x61, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52,
	0x08, 0x6c, 0x65, 0x61, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x42, 0x06, 0x0a, 0x04, 0x6e, 0x6f, 0x64,
	0x65, 0x22, 0x7c, 0x0a, 0x0c, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4e, 0x6f, 0x64,
	0x65, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x5f, 0x62, 0x69,
	0x74, 0x6d, 0x61, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0e, 0x63, 0x68, 0x69, 0x6c,
	0x64, 0x72, 0x65, 0x6e, 0x42, 0x69, 0x74, 0x6d, 0x61, 0x70, 0x12, 0x43, 0x0a, 0x08, 0x63, 0x68,
	0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x6f,
	0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x69, 0x6e, 0x67,
	0x33, 0x5f, 0x31, 0x2e, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65,
	0x43, 0x68, 0x69, 0x6c, 0x64, 0x52, 0x08, 0x63, 0x68, 0x69, 0x6c, 0x64, 0x72, 0x65, 0x6e, 0x22,
	0x5e, 0x0a, 0x11, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x4e, 0x6f, 0x64, 0x65, 0x43,
	0x68, 0x69, 0x6c, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16,
	0x0a, 0x06, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06,
	0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x73, 0x5f, 0x6c, 0x65, 0x61,
	0x66, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x4c, 0x65, 0x61, 0x66, 0x22,
	0x74, 0x0a, 0x08, 0x4c, 0x65, 0x61, 0x66, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6b,
	0x65, 0x79, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x6b, 0x65, 0x79, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x21, 0x0a, 0x0c,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x44, 0x69, 0x67, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x11, 0x5a, 0x0f, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x69, 0x61,
	0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_offchainreporting3_1_jmt_proto_rawDescOnce sync.Once
	file_offchainreporting3_1_jmt_proto_rawDescData = file_offchainreporting3_1_jmt_proto_rawDesc
)

func file_offchainreporting3_1_jmt_proto_rawDescGZIP() []byte {
	file_offchainreporting3_1_jmt_proto_rawDescOnce.Do(func() {
		file_offchainreporting3_1_jmt_proto_rawDescData = protoimpl.X.CompressGZIP(file_offchainreporting3_1_jmt_proto_rawDescData)
	})
	return file_offchainreporting3_1_jmt_proto_rawDescData
}

var file_offchainreporting3_1_jmt_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_offchainreporting3_1_jmt_proto_goTypes = []interface{}{
	(*Node)(nil),              // 0: offchainreporting3_1.Node
	(*InternalNode)(nil),      // 1: offchainreporting3_1.InternalNode
	(*InternalNodeChild)(nil), // 2: offchainreporting3_1.InternalNodeChild
	(*LeafNode)(nil),          // 3: offchainreporting3_1.LeafNode
}
var file_offchainreporting3_1_jmt_proto_depIdxs = []int32{
	1, // 0: offchainreporting3_1.Node.internal_node:type_name -> offchainreporting3_1.InternalNode
	3, // 1: offchainreporting3_1.Node.leaf_node:type_name -> offchainreporting3_1.LeafNode
	2, // 2: offchainreporting3_1.InternalNode.children:type_name -> offchainreporting3_1.InternalNodeChild
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_offchainreporting3_1_jmt_proto_init() }
func file_offchainreporting3_1_jmt_proto_init() {
	if File_offchainreporting3_1_jmt_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_offchainreporting3_1_jmt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offchainreporting3_1_jmt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offchainreporting3_1_jmt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InternalNodeChild); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offchainreporting3_1_jmt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LeafNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_offchainreporting3_1_jmt_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Node_InternalNode)(nil),
		(*Node_LeafNode)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_offchainreporting3_1_jmt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_offchainreporting3_1_jmt_proto_goTypes,
		DependencyIndexes: file_offchainreporting3_1_jmt_proto_depIdxs,
		MessageInfos:      file_offchainreporting3_1_jmt_proto_msgTypes,
	}.Build()
	File_offchainreporting3_1_jmt_proto = out.File
	file_offchainreporting3_1_jmt_proto_rawDesc = nil
	file_offchainreporting3_1_jmt_proto_goTypes = nil
	file_offchainreporting3_1_jmt_proto_depIdxs = nil
}
