// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: offchainreporting3_1_blobs.proto

package serialization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LightCertifiedBlob struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChunkDigests                         [][]byte                               `protobuf:"bytes,1,rep,name=chunk_digests,json=chunkDigests,proto3" json:"chunk_digests,omitempty"`
	PayloadLength                        uint64                                 `protobuf:"varint,2,opt,name=payload_length,json=payloadLength,proto3" json:"payload_length,omitempty"`
	ExpirySeqNr                          uint64                                 `protobuf:"varint,3,opt,name=expiry_seq_nr,json=expirySeqNr,proto3" json:"expiry_seq_nr,omitempty"`
	Submitter                            uint32                                 `protobuf:"varint,4,opt,name=submitter,proto3" json:"submitter,omitempty"`
	AttributedBlobAvailabilitySignatures []*AttributedBlobAvailabilitySignature `protobuf:"bytes,5,rep,name=attributed_blob_availability_signatures,json=attributedBlobAvailabilitySignatures,proto3" json:"attributed_blob_availability_signatures,omitempty"`
}

func (x *LightCertifiedBlob) Reset() {
	*x = LightCertifiedBlob{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offchainreporting3_1_blobs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LightCertifiedBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightCertifiedBlob) ProtoMessage() {}

func (x *LightCertifiedBlob) ProtoReflect() protoreflect.Message {
	mi := &file_offchainreporting3_1_blobs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightCertifiedBlob.ProtoReflect.Descriptor instead.
func (*LightCertifiedBlob) Descriptor() ([]byte, []int) {
	return file_offchainreporting3_1_blobs_proto_rawDescGZIP(), []int{0}
}

func (x *LightCertifiedBlob) GetChunkDigests() [][]byte {
	if x != nil {
		return x.ChunkDigests
	}
	return nil
}

func (x *LightCertifiedBlob) GetPayloadLength() uint64 {
	if x != nil {
		return x.PayloadLength
	}
	return 0
}

func (x *LightCertifiedBlob) GetExpirySeqNr() uint64 {
	if x != nil {
		return x.ExpirySeqNr
	}
	return 0
}

func (x *LightCertifiedBlob) GetSubmitter() uint32 {
	if x != nil {
		return x.Submitter
	}
	return 0
}

func (x *LightCertifiedBlob) GetAttributedBlobAvailabilitySignatures() []*AttributedBlobAvailabilitySignature {
	if x != nil {
		return x.AttributedBlobAvailabilitySignatures
	}
	return nil
}

type AttributedBlobAvailabilitySignature struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Signature []byte `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Signer    uint32 `protobuf:"varint,2,opt,name=signer,proto3" json:"signer,omitempty"`
}

func (x *AttributedBlobAvailabilitySignature) Reset() {
	*x = AttributedBlobAvailabilitySignature{}
	if protoimpl.UnsafeEnabled {
		mi := &file_offchainreporting3_1_blobs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributedBlobAvailabilitySignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributedBlobAvailabilitySignature) ProtoMessage() {}

func (x *AttributedBlobAvailabilitySignature) ProtoReflect() protoreflect.Message {
	mi := &file_offchainreporting3_1_blobs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributedBlobAvailabilitySignature.ProtoReflect.Descriptor instead.
func (*AttributedBlobAvailabilitySignature) Descriptor() ([]byte, []int) {
	return file_offchainreporting3_1_blobs_proto_rawDescGZIP(), []int{1}
}

func (x *AttributedBlobAvailabilitySignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *AttributedBlobAvailabilitySignature) GetSigner() uint32 {
	if x != nil {
		return x.Signer
	}
	return 0
}

var File_offchainreporting3_1_blobs_proto protoreflect.FileDescriptor

var file_offchainreporting3_1_blobs_proto_rawDesc = []byte{
	0x0a, 0x20, 0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x33, 0x5f, 0x31, 0x5f, 0x62, 0x6c, 0x6f, 0x62, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x65, 0x70, 0x6f,
	0x72, 0x74, 0x69, 0x6e, 0x67, 0x33, 0x5f, 0x31, 0x22, 0xb5, 0x02, 0x0a, 0x12, 0x4c, 0x69, 0x67,
	0x68, 0x74, 0x43, 0x65, 0x72, 0x74, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x12,
	0x23, 0x0a, 0x0d, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x69, 0x67, 0x65, 0x73, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0c, 0x52, 0x0c, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x69, 0x67,
	0x65, 0x73, 0x74, 0x73, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x5f,
	0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x12, 0x22, 0x0a, 0x0d, 0x65,
	0x78, 0x70, 0x69, 0x72, 0x79, 0x5f, 0x73, 0x65, 0x71, 0x5f, 0x6e, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x69, 0x72, 0x79, 0x53, 0x65, 0x71, 0x4e, 0x72, 0x12,
	0x1c, 0x0a, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x74, 0x65, 0x72, 0x12, 0x90, 0x01,
	0x0a, 0x27, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x6c, 0x6f,
	0x62, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x5f, 0x73,
	0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x39, 0x2e, 0x6f, 0x66, 0x66, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x69, 0x6e, 0x67, 0x33, 0x5f, 0x31, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65,
	0x64, 0x42, 0x6c, 0x6f, 0x62, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74,
	0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x52, 0x24, 0x61, 0x74, 0x74, 0x72,
	0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61,
	0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73,
	0x22, 0x5b, 0x0a, 0x23, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x64, 0x42, 0x6c,
	0x6f, 0x62, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x69, 0x6c, 0x69, 0x74, 0x79, 0x53, 0x69,
	0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e,
	0x61, 0x74, 0x75, 0x72, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x42, 0x11, 0x5a,
	0x0f, 0x2e, 0x3b, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_offchainreporting3_1_blobs_proto_rawDescOnce sync.Once
	file_offchainreporting3_1_blobs_proto_rawDescData = file_offchainreporting3_1_blobs_proto_rawDesc
)

func file_offchainreporting3_1_blobs_proto_rawDescGZIP() []byte {
	file_offchainreporting3_1_blobs_proto_rawDescOnce.Do(func() {
		file_offchainreporting3_1_blobs_proto_rawDescData = protoimpl.X.CompressGZIP(file_offchainreporting3_1_blobs_proto_rawDescData)
	})
	return file_offchainreporting3_1_blobs_proto_rawDescData
}

var file_offchainreporting3_1_blobs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_offchainreporting3_1_blobs_proto_goTypes = []interface{}{
	(*LightCertifiedBlob)(nil),                  // 0: offchainreporting3_1.LightCertifiedBlob
	(*AttributedBlobAvailabilitySignature)(nil), // 1: offchainreporting3_1.AttributedBlobAvailabilitySignature
}
var file_offchainreporting3_1_blobs_proto_depIdxs = []int32{
	1, // 0: offchainreporting3_1.LightCertifiedBlob.attributed_blob_availability_signatures:type_name -> offchainreporting3_1.AttributedBlobAvailabilitySignature
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_offchainreporting3_1_blobs_proto_init() }
func file_offchainreporting3_1_blobs_proto_init() {
	if File_offchainreporting3_1_blobs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_offchainreporting3_1_blobs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LightCertifiedBlob); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_offchainreporting3_1_blobs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributedBlobAvailabilitySignature); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_offchainreporting3_1_blobs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_offchainreporting3_1_blobs_proto_goTypes,
		DependencyIndexes: file_offchainreporting3_1_blobs_proto_depIdxs,
		MessageInfos:      file_offchainreporting3_1_blobs_proto_msgTypes,
	}.Build()
	File_offchainreporting3_1_blobs_proto = out.File
	file_offchainreporting3_1_blobs_proto_rawDesc = nil
	file_offchainreporting3_1_blobs_proto_goTypes = nil
	file_offchainreporting3_1_blobs_proto_depIdxs = nil
}
